class_name ModuleManifest
extends Resource
## Declares a feature module's identity and its dependencies.
##
## Rule 36 requires every dependency to be explicit. A module that needs
## another module says so here, where the registry can check it, rather than
## discovering the coupling at runtime through a failed call.
##
## Depending on Core is implicit and must not be listed: Core is the contract
## layer every module may know.

@export var id: StringName = &""
@export var display_name: String = ""
@export var version: String = "0.1.0"
@export_multiline var description: String = ""

## Modules that must be registered for this one to function. Registration
## fails if any are missing.
@export var requires: Array[StringName] = []

## Modules this one will integrate with when present, and function without
## when absent. Missing optional modules are a valid state, not an error
## (rule 31).
@export var optional: Array[StringName] = []

## Modules whose [i]files[/i] must be on disk for this module's scripts to
## parse at all.
##
## [b]A different relation from the two above, and the one rule 10 is actually
## about.[/b] [member requires] and [member optional] both describe
## registration: what must be enabled, and what is integrated with when it is.
## Neither says whether the folder has to exist, and in GDScript that is a
## separate question with a harsher answer -- naming a [code]class_name[/code]
## anywhere in a script body is resolved when the script is parsed, before any
## module is registered and regardless of whether it ever is.
##
## Without this field the manifest could be accurate and still mislead.
## [code]module.factions[/code] truthfully declared [code]requires = [][/code],
## because a [FactionComponent] needs nothing about Entity registered -- while
## being unable to parse without Entity, because it extends
## [FrameworkComponent] and that class lives in [code]entity/[/code]. A project
## reading "Entity: optional" and deleting the folder got a build that would
## not load, and nothing in the manifest had lied to it.
##
## Generated by [code]ParseDependencyScanner[/code] rather than written by
## hand, and [code]test_module_removability.gd[/code] fails when a list and its
## source disagree -- in either direction, because an entry nobody needs is how
## a module stops being deletable on paper years after it stopped being so in
## fact.
@export var parse_requires: Array[StringName] = []


func validate() -> ValidationResult:
	var result := ValidationResult.new()
	if id == &"":
		result.add_error(
			&"module.missing_id", "Module manifest has no id.", resource_path, "id"
		)
	if requires.has(id):
		result.add_error(
			&"module.self_dependency",
			"Module '%s' lists itself as a required dependency." % id,
			resource_path,
			"requires"
		)
	if parse_requires.has(id):
		result.add_error(
			&"module.self_parse_dependency",
			"Module '%s' lists itself among the files it cannot parse without." % id,
			resource_path,
			"parse_requires"
		)
	# A module appearing in both requires and parse_requires is not ambiguous
	# the way requires-and-optional is: one says "must be registered", the
	# other "must be on disk", and a module that must be registered is one
	# whose classes this module almost certainly names. So there is
	# deliberately no check for that overlap.
	for dependency in requires:
		if optional.has(dependency):
			result.add_warning(
				&"module.ambiguous_dependency",
				"Module '%s' lists '%s' as both required and optional." % [id, dependency],
				resource_path,
				"requires"
			)
	return result


func get_debug_name() -> String:
	if not display_name.is_empty():
		return "%s (%s)" % [display_name, id]
	return str(id) if id != &"" else "<unnamed module>"
