class_name DocGenerator
extends RefCounted
## Builds the reference documentation from the source it documents.
##
## [b]Generated, because hand-written reference docs are wrong within a
## month.[/b] Every module list and class index in this repository is produced
## from the manifests and the doc comments themselves, and
## [code]test_documentation.gd[/code] fails when the committed file no longer
## matches what this would produce. Prose that requires judgement -- the
## migration guide, the README -- stays hand-written, because generating it
## would only produce prose nobody wrote.
##
## Lives in [code]tools/[/code] rather than in the addon. It is build
## machinery, and shipping it inside the addon would put a Markdown generator
## in every game that installs the framework (rule 29 in spirit).

const ADDON_ROOT: String = "res://addons/universal_gameplay"

const GENERATED_NOTICE: String = (
	"<!-- Generated by tools/generate_docs.gd. Do not edit by hand: "
	+ "test_documentation.gd fails when this file and the source disagree. -->"
)


# --- Module reference -----------------------------------------------------

## The module enablement reference: what each module is, what it needs, and
## what it will use if present.
static func build_module_reference() -> String:
	var lines: Array[String] = []
	lines.append(GENERATED_NOTICE)
	lines.append("")
	lines.append("# Modules")
	lines.append("")
	lines.append(
		"Every feature the framework ships is a module, and every module is optional."
	)
	lines.append(
		"A project names the ones it wants in its `FrameworkSettings.enabled_modules`"
	)
	lines.append(
		"and the framework brings them up in dependency order. Nothing is registered"
	)
	lines.append("on your behalf: a list missing a required module is refused, with the")
	lines.append("missing ids named.")
	lines.append("")
	lines.append("**Required** modules must be enabled too, or the list will not resolve.")
	lines.append("**Optional** modules are integrated with when present and done without")
	lines.append("when absent -- a missing optional module is a valid state, never an error.")
	lines.append("")
	lines.append("| Module | Id | Requires | Optional |")
	lines.append("| --- | --- | --- | --- |")

	for id in ModuleCatalog.get_ids():
		var manifest := ModuleCatalog.get_manifest(id)
		lines.append(
			"| %s | `%s` | %s | %s |"
			% [
				manifest.display_name,
				id,
				_id_list(manifest.requires),
				_id_list(manifest.optional),
			]
		)

	lines.append("")
	lines.append("## What each module is for")
	lines.append("")
	for id in ModuleCatalog.get_ids():
		var manifest := ModuleCatalog.get_manifest(id)
		lines.append("### %s" % manifest.display_name)
		lines.append("")
		lines.append("`%s` — `%s`" % [id, ModuleCatalog.get_script_path(id)])
		lines.append("")
		lines.append(_single_line(manifest.description))
		lines.append("")

	return "\n".join(lines)


# --- Class index ----------------------------------------------------------

## An index of every global class the addon defines, grouped by the folder it
## lives in, with the first line of its own documentation.
static func build_class_index() -> String:
	var lines: Array[String] = []
	lines.append(GENERATED_NOTICE)
	lines.append("")
	lines.append("# API reference")
	lines.append("")
	lines.append(
		"Every `class_name` the addon defines. The summary is the first line of the"
	)
	lines.append(
		"class's own documentation comment; the full text is in the source file, and"
	)
	lines.append("in Godot's built-in help once the addon is enabled.")
	lines.append("")
	lines.append(
		"Scripts with no `class_name` are omitted deliberately. Autoloads have none"
	)
	lines.append(
		"(a global class would collide with the singleton), modules have none (they are"
	)
	lines.append(
		"instantiated by the catalog, not referenced globally), and events have none"
	)
	lines.append("(they are matched by name on the bus).")
	lines.append("")

	var by_folder: Dictionary[String, Array] = {}
	for path in _find_scripts(ADDON_ROOT):
		var entry := _describe_script(path)
		if entry.is_empty():
			continue
		var folder: String = path.get_base_dir().replace(ADDON_ROOT + "/", "")
		if folder == ADDON_ROOT:
			folder = "."
		if not by_folder.has(folder):
			by_folder[folder] = []
		by_folder[folder].append(entry)

	var folders: Array[String] = []
	folders.assign(by_folder.keys())
	folders.sort()

	for folder in folders:
		lines.append("## `%s/`" % folder)
		lines.append("")
		lines.append("| Class | Extends | Summary |")
		lines.append("| --- | --- | --- |")
		var entries: Array = by_folder[folder]
		entries.sort_custom(
			func(a: Dictionary, b: Dictionary) -> bool: return a["name"] < b["name"]
		)
		for entry in entries:
			lines.append(
				"| `%s` | `%s` | %s |"
				% [entry["name"], entry["extends"], _escape_cell(entry["summary"])]
			)
		lines.append("")

	return "\n".join(lines)


## Scripts under the addon that declare a [code]class_name[/code] but no
## documentation comment for it.
##
## An undocumented public class is one a project has to read the body of to
## use, which is the state this whole file exists to prevent.
static func find_undocumented_classes() -> Array[String]:
	var missing: Array[String] = []
	for path in _find_scripts(ADDON_ROOT):
		var entry := _describe_script(path)
		if entry.is_empty():
			continue
		if str(entry["summary"]).strip_edges().is_empty():
			missing.append(path)
	return missing


# --- Parsing --------------------------------------------------------------

## Name, base class and summary for one script, or an empty dictionary when it
## declares no global class.
##
## Deliberately a line reader rather than anything cleverer. The alternative is
## instantiating every script in the addon to interrogate it, which runs
## whatever those scripts do at load time just to write a table of contents.
static func _describe_script(path: String) -> Dictionary:
	var file := FileAccess.open(path, FileAccess.READ)
	if file == null:
		return {}

	var class_id := ""
	var base := ""
	var summary := ""
	var in_header := false

	while not file.eof_reached():
		var line := file.get_line()
		var trimmed := line.strip_edges()

		if trimmed.begins_with("class_name "):
			class_id = trimmed.substr(11).strip_edges()
			in_header = true
			continue
		if trimmed.begins_with("extends "):
			if class_id == "":
				# extends must immediately follow class_name, so reaching one
				# first means this script declares no global class. Nothing
				# further in the file can change that.
				break
			base = trimmed.substr(8).strip_edges()
			continue
		if _is_doc_comment(trimmed) and class_id != "":
			var text := trimmed.substr(2).strip_edges()
			if text.is_empty():
				# A bare "##" ends the summary paragraph. Everything after it
				# is detail, and detail belongs in the source, not in a table.
				break
			summary = text if summary.is_empty() else "%s %s" % [summary, text]
			if summary.ends_with("."):
				break
			continue
		# The documentation block must follow the header immediately. A blank
		# line or any statement between them means the class has none, and
		# whatever "##" appears further down belongs to a member.
		if in_header and not trimmed.begins_with("extends ") and not trimmed.is_empty():
			break
		if in_header and trimmed.is_empty():
			break

	file.close()
	if class_id == "":
		return {}
	return {"name": class_id, "extends": base, "summary": _first_sentence(summary), "path": path}


## The first sentence of a summary paragraph.
##
## Cutting at the first line instead would truncate mid-word, and a table of
## contents full of half-sentences is worse than one with long entries.
static func _first_sentence(text: String) -> String:
	var stop := text.find(". ")
	if stop < 0:
		return text
	return text.substr(0, stop + 1)


static func _is_doc_comment(trimmed: String) -> bool:
	return trimmed.begins_with("##")


static func _id_list(ids: Array[StringName]) -> String:
	if ids.is_empty():
		return "—"
	var parts: Array[String] = []
	for id in ids:
		parts.append("`%s`" % id)
	parts.sort()
	return ", ".join(parts)


## Collapses a multi-line manifest description into one line of Markdown.
static func _single_line(text: String) -> String:
	var flattened := text.replace("\n", " ").replace("\t", " ")
	while flattened.contains("  "):
		flattened = flattened.replace("  ", " ")
	return flattened.strip_edges()


## Makes a summary safe inside a Markdown table cell.
static func _escape_cell(text: String) -> String:
	return _single_line(text).replace("|", "\\|")


static func _find_scripts(directory: String) -> Array[String]:
	var found: Array[String] = []
	var dir := DirAccess.open(directory)
	if dir == null:
		return found
	dir.list_dir_begin()
	var entry := dir.get_next()
	while entry != "":
		if not entry.begins_with("."):
			var full_path := directory.path_join(entry)
			if dir.current_is_dir():
				found.append_array(_find_scripts(full_path))
			elif entry.get_extension() == "gd":
				found.append(full_path)
		entry = dir.get_next()
	dir.list_dir_end()
	found.sort()
	return found
